# .github/workflows/test_boletin_automation.yml
name: Test Boletin Oficial Automation

on:
  workflow_dispatch: # Esto es clave para poder ejecutarlo manualmente

jobs:
  test_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Vercel Deployment URL for Test
        id: vercel_url_test
        run: |
          echo "VERCEL_URL=https://boletin.encriollo.com.ar" >> $GITHUB_ENV

      - name: Run Full Automation Test (SUCCESS)
        run: |
          echo "Corriendo prueba de flujo completo (éxito)..."
          curl -X GET "${{ env.VERCEL_URL }}/api/testing" -H "Content-Type: application/json"
        env:
          VERCEL_URL: ${{ env.VERCEL_URL }}

      - name: Run Full Automation Test (SIMULATE GENERAL ERROR)
        run: |
          echo "Corriendo prueba de flujo completo (simulando error general)..."
          curl -f -X GET "${{ env.VERCEL_URL }}/api/testing?simulate_error=true" -H "Content-Type: application/json"
        env:
          VERCEL_URL: ${{ env.VERCEL_URL }}
        continue-on-error: true # Permite que el workflow continúe a pesar de este fallo simulado

      - name: Run Obtener.py Test (SIMULATE ERROR)
        run: |
          echo "Corriendo prueba de Obtener.py (simulando error)..."
          curl -f -X GET "${{ env.VERCEL_URL }}/api/testing?simulate_error_step=obtener" -H "Content-Type: application/json"
        env:
          VERCEL_URL: ${{ env.VERCEL_URL }}
        continue-on-error: true

      - name: Run Resumir.py Test (SIMULATE LLM ERROR)
        run: |
          echo "Corriendo prueba de Resumir.py (simulando error de LLM)..."
          curl -f -X GET "${{ env.VERCEL_URL }}/api/testing?simulate_llm_error=true" -H "Content-Type: application/json"
        env:
          VERCEL_URL: ${{ env.VERCEL_URL }}
        continue-on-error: true
